# SPDX-FileCopyrightText: © 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Install pkg-config
  ansible.builtin.apt:
    pkg: pkg-config
    state: latest
  become: true

# required by community.general.github_release
- name: Install github3.py
  ansible.builtin.pip:
    name: github3.py
    state: latest
  environment:
    # github3.py may invoke rust compiler
    PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"

- name: Git query latest lingo release
  community.general.github_release:
    user: lf-lang
    repo: lingo
    action: latest_release
  register: lingo_release

- name: Create cache folder "{{ ansible_env.HOME }}/.cache"/lf-lang
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.cache/lf-lang"
    state: directory

- name: Git clone lf-lang/lingo tag {{ lingo_release.tag }}
  ansible.builtin.git:
    repo: "https://github.com/lf-lang/lingo"
    dest: "{{ ansible_env.HOME }}/.cache/lf-lang/lingo"
    version: "{{ lingo_release.tag }}"
    single_branch: true
    force: true

- name: Set default rust version to stable
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.cargo/bin/rustup default stable"
  changed_when: false

- name: Install lingo
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.cargo/bin/cargo install --path {{ ansible_env.HOME }}/.cache/lf-lang/lingo"
    creates: "{{ ansible_env.HOME }}/.cargo/bin/lingo"
